import CapacityReservation_ from './CapacityReservation';
import CapacityReservationFleet_ from './CapacityReservationFleet';
import ClientVpnAuthorizationRule_ from './ClientVpnAuthorizationRule';
import ClientVpnEndpoint_ from './ClientVpnEndpoint';
import ClientVpnRoute_ from './ClientVpnRoute';
import ClientVpnTargetNetworkAssociation_ from './ClientVpnTargetNetworkAssociation';
import CustomerGateway_ from './CustomerGateway';
import DHCPOptions_ from './DHCPOptions';
import EC2Fleet_ from './EC2Fleet';
import EIP_ from './EIP';
import EIPAssociation_ from './EIPAssociation';
import EgressOnlyInternetGateway_ from './EgressOnlyInternetGateway';
import EnclaveCertificateIamRoleAssociation_ from './EnclaveCertificateIamRoleAssociation';
import FlowLog_ from './FlowLog';
import GatewayRouteTableAssociation_ from './GatewayRouteTableAssociation';
import Host_ from './Host';
import Instance_ from './Instance';
import InternetGateway_ from './InternetGateway';
import LaunchTemplate_ from './LaunchTemplate';
import LocalGatewayRoute_ from './LocalGatewayRoute';
import LocalGatewayRouteTableVPCAssociation_ from './LocalGatewayRouteTableVPCAssociation';
import NatGateway_ from './NatGateway';
import NetworkAcl_ from './NetworkAcl';
import NetworkAclEntry_ from './NetworkAclEntry';
import NetworkInsightsAnalysis_ from './NetworkInsightsAnalysis';
import NetworkInsightsPath_ from './NetworkInsightsPath';
import NetworkInterface_ from './NetworkInterface';
import NetworkInterfaceAttachment_ from './NetworkInterfaceAttachment';
import NetworkInterfacePermission_ from './NetworkInterfacePermission';
import PlacementGroup_ from './PlacementGroup';
import PrefixList_ from './PrefixList';
import Route_ from './Route';
import RouteTable_ from './RouteTable';
import SecurityGroup_ from './SecurityGroup';
import SecurityGroupEgress_ from './SecurityGroupEgress';
import SecurityGroupIngress_ from './SecurityGroupIngress';
import SpotFleet_ from './SpotFleet';
import Subnet_ from './Subnet';
import SubnetCidrBlock_ from './SubnetCidrBlock';
import SubnetNetworkAclAssociation_ from './SubnetNetworkAclAssociation';
import SubnetRouteTableAssociation_ from './SubnetRouteTableAssociation';
import TrafficMirrorFilter_ from './TrafficMirrorFilter';
import TrafficMirrorFilterRule_ from './TrafficMirrorFilterRule';
import TrafficMirrorSession_ from './TrafficMirrorSession';
import TrafficMirrorTarget_ from './TrafficMirrorTarget';
import TransitGateway_ from './TransitGateway';
import TransitGatewayAttachment_ from './TransitGatewayAttachment';
import TransitGatewayConnect_ from './TransitGatewayConnect';
import TransitGatewayMulticastDomain_ from './TransitGatewayMulticastDomain';
import TransitGatewayMulticastDomainAssociation_ from './TransitGatewayMulticastDomainAssociation';
import TransitGatewayMulticastGroupMember_ from './TransitGatewayMulticastGroupMember';
import TransitGatewayMulticastGroupSource_ from './TransitGatewayMulticastGroupSource';
import TransitGatewayPeeringAttachment_ from './TransitGatewayPeeringAttachment';
import TransitGatewayRoute_ from './TransitGatewayRoute';
import TransitGatewayRouteTable_ from './TransitGatewayRouteTable';
import TransitGatewayRouteTableAssociation_ from './TransitGatewayRouteTableAssociation';
import TransitGatewayRouteTablePropagation_ from './TransitGatewayRouteTablePropagation';
import TransitGatewayVpcAttachment_ from './TransitGatewayVpcAttachment';
import VPC_ from './VPC';
import VPCCidrBlock_ from './VPCCidrBlock';
import VPCDHCPOptionsAssociation_ from './VPCDHCPOptionsAssociation';
import VPCEndpoint_ from './VPCEndpoint';
import VPCEndpointConnectionNotification_ from './VPCEndpointConnectionNotification';
import VPCEndpointService_ from './VPCEndpointService';
import VPCEndpointServicePermissions_ from './VPCEndpointServicePermissions';
import VPCGatewayAttachment_ from './VPCGatewayAttachment';
import VPCPeeringConnection_ from './VPCPeeringConnection';
import VPNConnection_ from './VPNConnection';
import VPNConnectionRoute_ from './VPNConnectionRoute';
import VPNGateway_ from './VPNGateway';
import VPNGatewayRoutePropagation_ from './VPNGatewayRoutePropagation';
import Volume_ from './Volume';
import VolumeAttachment_ from './VolumeAttachment';

export namespace EC2 {
  export const CapacityReservation = CapacityReservation_;
  export const CapacityReservationFleet = CapacityReservationFleet_;
  export const ClientVpnAuthorizationRule = ClientVpnAuthorizationRule_;
  export const ClientVpnEndpoint = ClientVpnEndpoint_;
  export const ClientVpnRoute = ClientVpnRoute_;
  export const ClientVpnTargetNetworkAssociation =
    ClientVpnTargetNetworkAssociation_;
  export const CustomerGateway = CustomerGateway_;
  export const DHCPOptions = DHCPOptions_;
  export const EC2Fleet = EC2Fleet_;
  export const EIP = EIP_;
  export const EIPAssociation = EIPAssociation_;
  export const EgressOnlyInternetGateway = EgressOnlyInternetGateway_;
  export const EnclaveCertificateIamRoleAssociation =
    EnclaveCertificateIamRoleAssociation_;
  export const FlowLog = FlowLog_;
  export const GatewayRouteTableAssociation = GatewayRouteTableAssociation_;
  export const Host = Host_;
  export const Instance = Instance_;
  export const InternetGateway = InternetGateway_;
  export const LaunchTemplate = LaunchTemplate_;
  export const LocalGatewayRoute = LocalGatewayRoute_;
  export const LocalGatewayRouteTableVPCAssociation =
    LocalGatewayRouteTableVPCAssociation_;
  export const NatGateway = NatGateway_;
  export const NetworkAcl = NetworkAcl_;
  export const NetworkAclEntry = NetworkAclEntry_;
  export const NetworkInsightsAnalysis = NetworkInsightsAnalysis_;
  export const NetworkInsightsPath = NetworkInsightsPath_;
  export const NetworkInterface = NetworkInterface_;
  export const NetworkInterfaceAttachment = NetworkInterfaceAttachment_;
  export const NetworkInterfacePermission = NetworkInterfacePermission_;
  export const PlacementGroup = PlacementGroup_;
  export const PrefixList = PrefixList_;
  export const Route = Route_;
  export const RouteTable = RouteTable_;
  export const SecurityGroup = SecurityGroup_;
  export const SecurityGroupEgress = SecurityGroupEgress_;
  export const SecurityGroupIngress = SecurityGroupIngress_;
  export const SpotFleet = SpotFleet_;
  export const Subnet = Subnet_;
  export const SubnetCidrBlock = SubnetCidrBlock_;
  export const SubnetNetworkAclAssociation = SubnetNetworkAclAssociation_;
  export const SubnetRouteTableAssociation = SubnetRouteTableAssociation_;
  export const TrafficMirrorFilter = TrafficMirrorFilter_;
  export const TrafficMirrorFilterRule = TrafficMirrorFilterRule_;
  export const TrafficMirrorSession = TrafficMirrorSession_;
  export const TrafficMirrorTarget = TrafficMirrorTarget_;
  export const TransitGateway = TransitGateway_;
  export const TransitGatewayAttachment = TransitGatewayAttachment_;
  export const TransitGatewayConnect = TransitGatewayConnect_;
  export const TransitGatewayMulticastDomain = TransitGatewayMulticastDomain_;
  export const TransitGatewayMulticastDomainAssociation =
    TransitGatewayMulticastDomainAssociation_;
  export const TransitGatewayMulticastGroupMember =
    TransitGatewayMulticastGroupMember_;
  export const TransitGatewayMulticastGroupSource =
    TransitGatewayMulticastGroupSource_;
  export const TransitGatewayPeeringAttachment =
    TransitGatewayPeeringAttachment_;
  export const TransitGatewayRoute = TransitGatewayRoute_;
  export const TransitGatewayRouteTable = TransitGatewayRouteTable_;
  export const TransitGatewayRouteTableAssociation =
    TransitGatewayRouteTableAssociation_;
  export const TransitGatewayRouteTablePropagation =
    TransitGatewayRouteTablePropagation_;
  export const TransitGatewayVpcAttachment = TransitGatewayVpcAttachment_;
  export const VPC = VPC_;
  export const VPCCidrBlock = VPCCidrBlock_;
  export const VPCDHCPOptionsAssociation = VPCDHCPOptionsAssociation_;
  export const VPCEndpoint = VPCEndpoint_;
  export const VPCEndpointConnectionNotification =
    VPCEndpointConnectionNotification_;
  export const VPCEndpointService = VPCEndpointService_;
  export const VPCEndpointServicePermissions = VPCEndpointServicePermissions_;
  export const VPCGatewayAttachment = VPCGatewayAttachment_;
  export const VPCPeeringConnection = VPCPeeringConnection_;
  export const VPNConnection = VPNConnection_;
  export const VPNConnectionRoute = VPNConnectionRoute_;
  export const VPNGateway = VPNGateway_;
  export const VPNGatewayRoutePropagation = VPNGatewayRoutePropagation_;
  export const Volume = Volume_;
  export const VolumeAttachment = VolumeAttachment_;
}

export default EC2;
